title: 
logo: /assets/img/ja.jpeg
description: This is a photo of me taken with a Chaika 2 camera
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
livereload: true
diplay_github: true
github_url: https://www.github.com/jere357
display_huggingface: true
huggingface_url: https://www.huggingface.co/Cropinky
cv_url: /assets/cv/Jeronim_Matijevic_cv.pdf