title:
markdown: kramdown
usemathjax: true
logo: /assets/img/ja.jpeg
description: <b>Figure 1.</b> Jeronim with his 1070TI GPU, that has fans from aliexpress that don't really fit so he has to reapply the duct tape every now and then.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
livereload: true
diplay_github: true
github_url: https://www.github.com/jere357
display_huggingface: true
huggingface_url: https://www.huggingface.co/Cropinky
cv_url: /assets/cv/Jeronim_Matijevic_cv.pdf